export const MODULE_NAME = 'CORE';

/* actions */
export const CHECK_AUTH_REQUEST = `${MODULE_NAME}/CHECK_AUTH_REQUEST`;
export const CHECK_AUTH_SUCCESS = `${MODULE_NAME}/CHECK_AUTH_SUCCESS`;
export const CHECK_AUTH_FAILURE = `${MODULE_NAME}/CHECK_AUTH_FAILURE`;

export const SET_AUTH_LOADER = `${MODULE_NAME}/SET_AUTH_LOADER`;